# Generated by Django 5.1.2 on 2024-11-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=1000)),
                ('option_A', models.CharField(max_length=500)),
                ('option_B', models.CharField(max_length=500)),
                ('option_C', models.CharField(max_length=500)),
                ('option_D', models.CharField(max_length=500)),
                ('correct', models.CharField(max_length=500)),
            ],
        ),
    ]
